class GenreUtils {
  final List<String> _genreTitle = [
    "Fantasy",
    "Science Fiction",
    "Mystery",
    "Romance",
    "Thriller",
    "Horror",
    "Adventure",
    "Drama",
    "Historical Fiction",
    "Comedy",
    "Action",
    "Pirate Art",
    "Short Story",
    "Scientific",
    "Dystopian",
    "Supernatural",
    "Children's Story",
    "Adult Fiction",
    "Inspirational",
    "Mythology",
    "Mystical",
    "Picture Story",
    "Classic",
    "Scientific",
    "Superhero",
    "War",
    "Spiritual",
    "Psychological",
    "Serial Story",
    "Politics",
  ];

  List<String> get genreTitle => _genreTitle;
}
